name: mooSlidingLabels
author: marcelo.origoni
category: forms
tags: [forms, labels, sliding labels, forms labels]
docs: http://marcelo.origoni.com.ar/mooSlidingLabels/
demo: http://marcelo.origoni.com.ar/mooSlidingLabels/demo.php
current: 1.0